### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by Maxou44** [straxico/use-detect-keyboard-open#1]
Hello!

Thanks for your library, it's really cool :)

On iOS 12.5.6, I have an error ```window.visualViewport is undefined```, I worked around the problem on my side by not using the library on iOS. It could be nice to fix it on iOS devices when window.visualViewport is not supported, or at least, don't crash the whole page 😅

Have a good day,
Maxime

**Comment by straxico** [comment]
> Hello!
> 
> Thanks for your library, it's really cool :)
> 
> On iOS 12.5.6, I have an error `window.visualViewport is undefined`, I worked around the problem on my side by not using the library on iOS. It could be nice to fix it on iOS devices when window.visualViewport is not supported, or at least, don't crash the whole page sweat_smile
> 
> Have a good day, Maxime

Thanks Maxou44
At the moment, I have not found a clean solution to support old ios. So I just prevented the error from occurring

You are a handful and popular

**Comment by Maxou44** [comment]
Awesome ! Thanks for the update :)
